In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [46]:
def remove_no_used_col(df):
    return df.drop(["Unnamed: 0", "InitialIp", "EndIP", "Port", "Proto"],
           axis=1)


def change_class(x):
    if "Botnet" in x:
        return 1
    elif "Normal" in x:
        return 0 

    
def rename_labels(df):
    df["class"] = df["LabelName"].apply(change_class)
    return df.drop(["LabelName"],axis=1)


def rename_string_column(df):
    return df.rename({"State":"domain"},axis=1)


def remove_chars_until(df, k):
    df["domain"] = df["domain"].apply(lambda x: x[k:])
    return df


def drop_rows_empty_string(df):
    return df[df["domain"] != ""]

In [24]:
ctu19 = pd.read_csv("../Datasets/ctu19_result.csv")

In [10]:
ctu19.head(10)

,Unnamed: 0,InitialIp,EndIP,Port,Proto,State,LabelName
0,0,0.0.0.0,10.0.2.112,NaN,arp,2,Botnet
1,1,00:00:00:00:00:00,00:00:00:00:00:00,NaN,llc,1,Botnet
2,2,10.0.2.112,1.143.41.48,4451,udp,1,Botnet
3,3,10.0.2.112,1.161.56.125,4692,udp,960F0f0f0f0c0,Botnet
4,4,10.0.2.112,1.34.140.54,1016,udp,1,Botnet
5,5,10.0.2.112,1.34.176.189,25,tcp,"88*Y,Y0y*y*y*H*y*Y*H*Y+Y*y*y*y*y*Y0Y*Y+Y*y*y*y...",Botnet
6,6,10.0.2.112,1.34.176.189,80,tcp,"22,b,S*S,b,S*S,b,S*S,b,S*S,b,S*S,b,S*S,b,S*S,b...",Botnet
7,7,10.0.2.112,1.34.231.77,25,tcp,"88,Z*y00Y.Y*Y0H0h0Y+Y000Y*Y0y*Y,Y*Y*y*Y0y*y*h*...",Botnet
8,8,10.0.2.112,1.34.231.77,80,tcp,"93,z+w,I,w,S*Z,z,Z00000Z,Z0Z,z,Z*Z,I,Z0W,z,z,W...",Botnet
9,9,10.0.2.112,1.4.173.240,7661,udp,4,Botnet

In [14]:
ctu19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72463 entries, 0 to 72462
Data columns (total 7 columns):
Unnamed: 0    72463 non-null int64
InitialIp     72463 non-null object
EndIP         72463 non-null object
Port          72229 non-null object
Proto         72463 non-null object
State         72463 non-null object
LabelName     72463 non-null object
dtypes: int64(1), object(6)
memory usage: 3.9+ MB

In [30]:
ctu19["LabelName"].value_counts()

Botnet    67551
Normal     4912
Name: LabelName, dtype: int64

In [13]:
ctu19[ctu19["State"].str.len() > 5].shape

(25564, 7)

In [47]:
(ctu19.pipe(remove_no_used_col)
     .pipe(rename_labels)
     .pipe(rename_string_column)
     .pipe(remove_chars_until, 4)
     .pipe(drop_rows_empty_string))

                                                  domain  class
3                                              0f0f0f0c0      1
5      ,Y0y*y*y*H*y*Y*H*Y+Y*y*y*y*y*Y0Y*Y+Y*y*y*y*y*H...      1
6      ,S*S,b,S*S,b,S*S,b,S*S,b,S*S,b,S*S,b,S*S,b,S0S...      1
7      *y00Y.Y*Y0H0h0Y+Y000Y*Y0y*Y,Y*Y*y*Y0y*y*h*y0y0...      1
8      +w,I,w,S*Z,z,Z00000Z,Z0Z,z,Z*Z,I,Z0W,z,z,W00S,...      1
10     z0I0i0i0i0i0i0i0f0r00t0f0f0f0F0f0f0F0w0000A000...      1
11     0w0e0z00z0I0z0z0I0F0f0I0z0I0z00z0I0I0i0f0z0z0I...      1
12     0000000000000000000000000000000000000000000000...      1
18                                                   0a0      1
20     *y*y0Y*Y0y0Y00000Y*Y+Y*y*y0y00Y*Y+Y0y00y*H*y*H...      1
21     ,Z+S,Z,z,Y0H0y*y*Y00y*y0v00Y+Y0H0y*y0y*y0y000y...      1
22     000000000000000000000000y000000000000H00000000...      1
23     *y*H*Y+Y*y*h*Y0y00y000y0y*y00Y,y,Y+Y*H*y*H*y*y...      1
24     +y+Y,Y00Y*Y000Y+Y*Y000000Y*y*y*y*y0y0000Y*Y0Y+...      1
25     *y*y*Y+Y0H0Y*Y0y0Y*y0y000Y*Y*y*y*y*Y+y+Y*y*y*H...      1
26     000y00z0z000Z*Z0000Z+Z*z*z0z*Y,Y+z,y,Z*z*Z000Z...      1
35     0000000000000000000000000000000000000000000000...      1
36     0F0F0f0f0i0i0F0F0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f...      1
41                                                 0f0f0      1
48     000000000000000000000000x000000000x00000000000...      1
49                   0000000000x000000000000000000000000      1
50     000000000000000000000000000000r0000000000000Y,...      1
51                                     00000000000000000      1
52     00y000y0y00Y*Y00000000000000000000000000000000...      1
53     z*z0z000z0Z*Z0000Z*s0S,b,Z00000000000000000000...      1
54     0000000000Z.Z.R000000000000R.Z.Z.R000000000000...      1
55     00000000000000x000000000y00000000000000G000000...      1
56     0H0000y000000000Y00000000000000000000000000000...      1
57     0z0000000Z*z0s000S,b,Z000000000000000000000000...      1
58     0000000000z00000000000000000000000000000000000...      1
...                                                  ...    ...
72408                            +Y.H.y.z.Y+Z.y.y.y.y.Z+      0
72409                                    ,y+Y.Y*Y.Y*Y,Y.      0
72411                                            .z.Y.Y.      0
72413                                                .Z+      0
72415                                              ,y,y,      0
72416                                              .z.Y.      0
72417                                                  *      0
72419                                            .Z.Y.H.      0
72420                              .y.Y.Y.Y.Y,Y.y.Y*y+Y.      0
72421                                            *y+y+y,      0
72422              .Z.z.Y.Z+Z.I.z.Y.Y.Y+Z.Y*Y.Y,Y.Z,Y.Z*      0
72423                                          .Y.Y.Y.H.      0
72426                                              .y.Y.      0
72427                                      .y.Y,y,Y.Y,Y.      0
72428                                                ,Y*      0
72429                                                  .      0
72430                                              .Z,Z.      0
72431                                          +Z,z,y+Z.      0
72432                                              ,Y+Y.      0
72433                                                  +      0
72434                                                  .      0
72438                                  .y.Y.Y+Y.Y+Y.Y.Y.      0
72439  *Y,Y,Y,Y.Z.Z,Y.Y,H,Y.Y.y.Z.Y.Y,Y.y.Y.Y.Y.Z.Y.Y...      0
72441                          ,Y.x.y.Y*Y.Y.Y.Y+Y,H,Y.Y.      0
72442                              +Z.Y.Z,z,Y.Y.Z+z*Z.Z*      0
72444                  .Y,Z*z+Y.Y+Z,Y+Z,Z+Y.Z+y+Z,Z*Z+Z*      0
72448                              .H.Y.Z*Y.Y,Y.y.Y.Z*z*      0
72450              .Z,Z.Z.z.z.Y*Z.Y*Z.Y.Y*Y.Z.Z,Z.Z.Z.Z.      0
72452  ,V.Z,Z.z.z.V.Z+Z,Z.V.Z+Z.V.Z+z*V,V.Z,Z*Z.V.Z*i...      0
72456                                                  .      0

[27414 rows x 2 columns]